### ISSUE TITLE
Investigate logging usage when client and server run within the same process (single-threaded scheduler)

### ISSUE THREAD

**Issue by cpelley** [MetOffice/dagrunner#44]
```
--- Logging error ---
Traceback (most recent call last):
  File "/path/to/lib/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'hostname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/lib/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'hostname'
```

## Issues

- Potentially related to https://github.com/MetOffice/dagrunner/issues/39 somehow.

**Comment by cpelley** [comment]
I think this is a non-issue since the single-threaded scheduler has no trouble with the logger implemented.
